name: Metrics
on:
  schedule: 
    - cron: "0 * * * *"
  workflow_dispatch:
  push: 
    branches:
      - "master"
      - "main"
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}

          user: towan912
          base: header, activity, community, repositories
          config_octicon: yes
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          repositories_forks: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: fortune.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}

          user: towan912
          base: ""
          config_octicon: yes
          config_timezone: Asia/Tokyo
          plugin_fortune: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: latest_tweet.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}

          user: towan912
          base: ""
          config_octicon: yes
          config_timezone: Asia/Tokyo
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: towan912        
      - uses: lowlighter/metrics@latest
        with:
          filename: habit.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}

          user: towan912
          base: ""
          base_indepth: yes
          config_octicon: yes
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_lines: yes
          plugin_traffic: yes
          repositories_forks: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: wakatime_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}

          user: towan912
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
      - name: Get Spotify token
        env:
          CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SPOFITY_SECRET }}
          CODE: ${{ secrets.SPOTIFY_CODE }}
        run: |
          echo "SPOTIFY_TOKEN=$(curl -d client_id=$CLIENT_ID -d client_secret=$CLIENT_SECRET -d grant_type=authorization_code -d code=$CODE -d redirect_uri=https://localhost https://accounts.spotify.com/api/token  | jq '.[].refresh_token')" >> $GITHUB_ENV
      - uses: lowlighter/metrics@latest
        with:
          filename: spotify_recently_listed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST_ID }}

          user: towan912
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ env.SPOTIFY_TOKEN }}
          plugin_music_limit: 2
