# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          # committer_gist: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

          # Options
          user: towan912
          base: activity, community
          base_indepth: yes
          config_display: columns
          config_octicon: yes
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_lines: yes
          plugin_traffic: yes
          repositories_forks: yes
